"""empty message

Revision ID: 410e7865465c
Revises: 
Create Date: 2019-08-13 22:24:30.464674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410e7865465c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'post', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='unique')
    # ### end Alembic commands ###
